AllCops:
    Exclude:
        - lib/prometheus/client/version.rb

AlignHash:
    EnforcedHashRocketStyle: table

TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Metrics/AbcSize:
    Max: 18
